name: Build and test with Gradle

on:
  [pull_request]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  MIN_COVERAGE: 80
  
jobs:
  build-test-check-coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write
    steps:

    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Make Gradle Executable
      run: chmod +x ./gradlew

    - name: Get Jacoco Report
      run: ./gradlew jacocoReport

    - name: Jacoco Report to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths: |
          ${{ github.workspace }}/build/reports/jacoco/jacocoTestReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        title: Coverage report (requires  ${{ env.MIN_COVERAGE }}%)
        min-coverage-overall: ${{ env.MIN_COVERAGE }}
        min-coverage-changed-files: ${{ env.MIN_COVERAGE }}
        debug-mode: false
        update-comment: true

    - name: Require ${{ env.MIN_COVERAGE }}% coverage
      env:
        MIN: ${{ env.MIN_COVERAGE }}
        COVERAGE: ${{ steps.jacoco.outputs.coverage-overall }}

      if: env.COVERAGE < 80
      uses: actions/github-script@v6
      with:
        script: |
          core.setFailed('Overall coverage is less than ${{ env.MIN_COVERAGE }}%!')

  run-integration-test:
    needs: build-test-check-coverage
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
          java-version: '17'
          distribution: 'temurin'
          
    - name: Make Gradle Executable
      run: chmod +x ./gradlew

    - name: Run Integration Tests
      run: ./gradlew integrationTest
    
  build-and-push-image:
    needs: run-integration-test
    runs-on: ubuntu-latest
    permissions:
          contents: read
          packages: write
    steps: 

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make Gradle Executable
        run: chmod +x ./gradlew
     
      - name: Generate Bootable Jar
        run: |
          ./gradlew bootJar 
      
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            tags: |
              type=ref,event=branch
              type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
        run: echo ${{steps.meta.outputs.tags}}
    outputs:
      image: ${{steps.build-and-push-docker-image.outputs.imageFullName}}
      tags: ${{steps.build-and-push-docker-image.outputs.tags}}

  run-image:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    services:
      app:
        image: ${{needs.build-and-push-image.outputs.image}}:${{needs.build-and-push-image.outputs.tags}}
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        ports:
          - 8080:8080
        options: --health-cmd="curl -f http://localhost:8080/calculate" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4

  run-system-tests:
    needs: run-image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Gradle Executable
        run: chmod +x ./gradlew

      - name: Run System Integration Tests
        run: ./gradlew systemIntegrationTest

  deploy_simulation:
    needs: run-system-tests
    runs-on: ubuntu-latest
    steps:

      - name: Echo Image Name
        run: |
            echo "Deploying image: ghcr.io/${{ github.repository }}:${{ github.ref_name }}"
