name: Run Unit Tests and Checkstyle on Push
on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  MIN_COVERAGE: 80

jobs:

  build-test-checkstyle:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make Gradle Executable
        run: chmod +x ./gradlew

      - name: Run Tests
        run: ./gradlew test

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest
